### ISSUE TITLE
management command to update sites

### ISSUE THREAD

**Issue by allynt** [astrosat/django-astrosat-core#7]
By default Django creates a Sites object w/ the domain "example.com" and a default SITE_ID of 1.  In order for things like emails to make sense, this ought to be updated to use the _real_ domain.  That's an extra manual step that can easily be forgotten.  

To get around it in the example project, I have added a data migration. But this won't work for real deployments b/c we deploy to multiple environments.

Instead, I am going to write a management command that will update sites w/ a particular domain. That domain can either be passed in or retrieved from the environment.  That command should be run upon deployment and as needed.

**Comment by R2ZER0** [comment]
So is this a step that’ll have to be added to deployed container startup, like manage.py migrate?

**Comment by allynt** [comment]
Yes it is.  I will update the appropriate files when the time comes.
